# Generated by Django 5.2.1 on 2025-05-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
    ]
