# Generated by Django 5.2.1 on 2025-05-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
    ]
